# Generated by Django 3.2 on 2021-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usertasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectnames',
            options={'verbose_name': 'Project Name', 'verbose_name_plural': 'Project Names'},
        ),
        migrations.AlterModelOptions(
            name='usertasks',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='usertasks',
            name='end_time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
