# Generated by Django 3.2 on 2021-04-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210422_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertasks',
            old_name='Task_title',
            new_name='task_title',
        ),
    ]
