# Generated by Django 3.2 on 2021-04-22 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_task_title_usertasks_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertasks',
            name='projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.projectnames'),
            preserve_default=False,
        ),
    ]
